name: Deploy CV

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev google-chrome-stable
    
    - name: Set CHROME PATH
      run: |
        echo "CHROME_PATH=$(which google-chrome || which chromium || which chromium-browser)" >> $GITHUB_ENV
    
    - name: Install R packages
      run: |
        Rscript -e "install.packages('pak')"
        Rscript -e "pak::pak('rstudio/pagedown')"
        Rscript -e "install.packages(c('fs', 'tidyverse', 'glue'))"
    
    - name: Render HTML
      run: |
        Rscript -e "rmarkdown::render('jsun-cv.rmd', params = list(pdf_mode = FALSE), output_file = 'html/jsun-cv.html')"
        Rscript -e "pagedown::chrome_print(input = 'html/jsun-cv.html', output = 'html/jsun-cv.pdf')"
        # Rscript -e "tmp_html_cv_loc <- fs::file_temp(ext = '.html')"
        # Rscript -e "pagedown::chrome_print(input = tmp_html_cv_loc, output = 'html/jsun-cv.pdf')"
        

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
